### ISSUE TITLE
Create a subset of data to be displayed on cards

### ISSUE THREAD

**Issue by jberns** [codefordenver/cdphe-accessible-covid19#13] opened 2021-01-09 20:39 UTC
Currently the home component is looping through all of the fields in the data set.  A filter needs to be done so that the data can be ordered and displayed correctly on the home page to only show relevant data.

**Comment by a-scar** [comment] 2021-01-10 20:30
Hey there! I found this project while looking for a "good first issue". I'm fairly new to react and to contributing through GitHub, although I've been a developer for some years now. Anyway, by this issue do you mean to create some sort of data model that the incoming data can be assigned to? In order to be able to properly display certain fields? I wasn't quite sure you meant "filter" in terms of filtering a list based on criteria, or "filtering" the data such as I described. Also, I was looking at the other issue with number formats. Would that be dependent on this one? Being we would first need to know which fields to apply some sort of formatting to? Thank you! Looking forward to seeing how I can help.

**Comment by joel-oe-lacey** [comment] 2021-01-11 03:08
Hey there @a-scar, thanks for your interest! In essence, filtering out fields we don't need that aren't of much value to a user. 

If you'd like to get involved and have a little more context to go off, which may help answer some of your other questions, probably best to have a quick talk to run you through what we're working on. 

Feel free to pick a time that works best for you this week and I'd be happy to give you a rundown:
https://calendly.com/joellaceybusiness/lets-chat

As organizational context, this project is part of a Code for Denver initiative, so if you're generally interested in localized civic tech might be worth checking out a meeting, they're currently remote: 
https://www.meetup.com/CodeForDenver/

This is part of the Code for America umbrella, so if you're looking for a more local branch you can find yours here:
https://brigade.codeforamerica.org/

**Comment by a-scar** [comment] 2021-01-11 04:07
Thanks @joel-oe-lacey! Sure, I'll schedule some time for this week to get a brief overview of the project. Hopefully I can help!

I wasn't aware of code for America, but thanks for the recommendation. Looks like Philly has a group, I'll have to check it out. 

Talk to you soon :)

**Comment by jberns** [comment] 2021-01-16 16:26
@a-scar Thanks for wanting to take on this issue!
If you still want to work on this, take a look at the updated `<StatsCard>` component in `src/components/home/statscard`.  There is some new logic in there that can be extracted to a higher level to help filter down the data.

What I would like to make is an object that holds all of the logic for a single piece of data.  So the constants and logic in the current `<StatsCard>` component would be extracted to look something like:

```
{ 
cases: {
  labelType:  "negative",
  labelDatatypes: "integer",
  labelAlias:  "Cases",
},
name:  {
  labelType: "neutral",
},
tested: {
  labelType: "negative",
  labelDataTypes: "integer",
  labelAlias: "Tested For The First Time"
}
}
```

Then two changes would be required:
1) Loop through this new object, and if the labelType = "neutral" we would not show the card on the home page.
2) After extracting all the values from the `StatsCard` component, all the applicable data that helps format the card (i.e. `labelType, labelDataTypes, labelAlias`) should be passed in as props.

**Comment by a-scar** [comment] 2021-01-20 00:45
Hey @jberns thanks for the comment! My apologies for not getting back sooner. I pulled the latest code and have a good understanding so far of it. I do have a few questions regarding your post. I assume you mean to create a data model that will represent all the data that lives on each card. One of those fields will be a boolean that determines if that card is displayed or not. I'm a little confused as to what you meant by "extracting" data from the stat card component. Additionally, are those the the exact field names you would like for the data model? Also, how will I determine which field names should be shown or not (best judgement?). Let me know if that all makes sense, and I'll be glad to get started!

**Comment by a-scar** [comment] 2021-01-20 01:47
Perhaps coming from a typescript world I am confusing the situation with data models. Essentially, I think it would be good to "groom" the data coming from the api into something a little easier to consume and understand. As well as determine things like "should we be using this data at all". Then that new object be passed into the stat cards as props.

**Comment by joel-oe-lacey** [comment] 2021-01-21 04:09
Hey just stopping in here to note that Wes has already done a little data normalization which is currently available on master, depending on when you last pulled @a-scar, might want to take that in. I'll defer to you both to determine best route on a model here, if that's desirable. 

I will add that the level of consolidation and abstraction we have for DailyStats might not be identical for different types of visualizations. So that might create a bunch of variable models for different endpoints. Given that it could be that this is better to be revisited as a point of refactoring and consolidation in later development, but I'll leave it to you both to make that judgment.

**Comment by galbwe** [comment] 2021-01-21 16:00
I think what @jberns is getting at is that the issue is now more about refactoring the rendering logic out of the StatsCard component and into a higher component like Home. I'd start by thinking about what changes need to be made to StatsCard so that its invocation in Home takes more parameters, like 
```
<StatsCard
       movement={current[key] - previous[key]}
       movementType={isDaily ? "daily" : "weekly"}
       total={current[key]}
       label={key}
       formatter={formatter}
       hideMovement={hideMovement}
       movementColor={movementColor}
       alias={alias}
/>
```
This way StatsCard doesn't have to "know" what the various labels are, their datatypes, whether they are positive, negative, neutral, etc.

@jberns, @joel-oe-lacey let me know if this is not in agreement with what what you had in mind.

**Closed as completed** 2021-04-06 01:46 UTC
Labels: good first issue
